name: CI

on: [push, pull_request]

jobs:
  ubuntu-18-04:
    name: Ubuntu 18.04 (CMake) [GCC]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd docker/ubuntu-18.04/
        docker build -t ubuntu .
        cd ../..
    - name: CMake Configure
      run: |
        echo $(pwd)
        docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake '-H.' -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWZ_ENABLE_WARNINGS:BOOL=ON -G"Ninja"
    - name: CMake Build
      run: docker run --rm -e "CI=true" -e GITHUB_WORKFLOW -e GITHUB_ACTION -e GITHUB_REPOSITORY -e "GITHUB_WORKSPACE=/code" -e GITHUB_SHA -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e MAKEFLAGS -v $(pwd):/code ubuntu cmake --build build
