on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

name: Draft Tag Release

jobs:
  if: startsWith(github.ref, 'refs/tags/') # sanity-check
  build:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        uses: past-due/action-gh-release@v1
        with:
          # Do not explicitly specify a tag_name, so this action takes the github.ref and parses it for just the tag
          body: |
            ### Do not publish this release until all of the artifacts have been uploaded by CI, and you've verified them according to the Release process. (Then remove this text block.)
            --------
            
            `warzone2100_win_x86_installer.exe` -- The main Windows build (full installer)
            `warzone2100_win_x86_portable.exe` -- The portable version of the Windows build (self contained -- install it anywhere!)
            `warzone2100_macOS.zip`  -- For macOS (10.10+)
            `warzone2100_src.tar.xz` -- The tarball for Linux / BSD / whatever systems. (full source / data)

            **IMPORTANT: To build from source, use the warzone2100_src.tar.xz tarball.**
            > The auto-generated GitHub "_Source code (zip) / (tar.gz)_" links do **_not_** include the Git-based autorevision information.
          draft: true
          prerelease: false
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
